### PR TITLE
kw2x: Update MKW22D5.h with proper MCU.

### PR DESCRIPTION
**Pull request by gebart**
It seems like the original header was for the K22 MCU (not KW22).

This needs some more changes to the startup procedure, at least adding a system_MKW22D5.h header and some related stuff in (board specific) system_MKW22D5.c.

### CODE REVIEW

**Comment by gebart** [comment]
The header is taken from Keil uVision's KWxx pack (file: .../`Kinetis_KWxx_DFP/1.0.0/Device/Include/MKW22D5.h`

See also #3 for the corresponding change necessary to `kinetis_common`

**Comment by jfischer-phytec-iot** [comment]
The header is deprecated and has no appropriate license.  #issuecomment-68589968

**Comment by gebart** [comment]
But using a K22 header for the KW22 is not the right way to go either.

I am assuming since the IRQ numbers are wrong and the RNG module is missing...

**Comment by jfischer-phytec-iot** [comment]
The CPU inside MKW22D512 is a MK22D, the IRQ numbers are the same, only RNG module is missing. I do not know why Freescale has made it so. I can merge #8df33c1 and adapt our current header.

**Comment by gebart** [comment]
@jfischer-phytec-iot I examined the changes again. The changes to the IRQ vector was mostly semantic, different names for the same IRQ, but the RNG is added and the UART3 module was deleted. I also found that the original K22 header is missing the CAU (Crypto Acceleration Unit) module memory map. RFSYS and RFVBAT are missing from the KW22 header, I do not know what these modules do.

What do you mean by the header is deprecated? Do you have any source for this information?

**Comment by jfischer-phytec-iot** [comment]
@gebart ok, funny, i will clear it with our FAE.

**Pull request closed without merging**
