### PR TITLE
Kinetis fixes after updating MKW22D5.h

### PR DESCRIPTION
**Pull request by gebart**
These changes were necessary in order to build after changing the kw2x header MKW22D5.h to the proper version in #2

### CODE REVIEW

**Comment by jfischer-phytec-iot** [comment]
Please check the using of RANDOM_RNGA_BASE, in some Headers it is just RNG or RNGA.

**Comment by Farthen** [comment]
The rename thing in cb8b2ed8b65d3bb6ef54bb9dc69a70f62bcbcb78 actually breaks my build because it's called LPTimer_IRQn there even in the CMSIS headers. I think we can't go without `#ifdef`s here (or `#ifdef` in `cpu-conf.h`).

**Comment by jfischer-phytec-iot** [comment]
@Farthen Yes we can, just add:

/*!
 * @addtogroup Backward_Compatibility_Symbols Backward Compatibility
 * @{
 */
#define LPTimer_IRQn                             LPTMR0_IRQn

to CMSIS header.

**Comment by Farthen** [comment]
Those header files are messy… But yeah, that works.

**Comment by gebart** [comment]
@jfischer-phytec-iot @Farthen Maybe the correct way is to keep the original code, before my changes to hwtimer and only add 

    #define LPTimer_IRQn LPTMR0_IRQn

to `cpu/kw2x/include/cpu-conf.h`?

**Comment by Farthen** [comment]
Are there devices with multiple LPTMR modules? If so do they have multiple interrupts?

**Comment by gebart** [comment]
I have not looked around, but the ones I have seen so far have only had one LPTMR module.

**Comment by jfischer-phytec-iot** [comment]
In MKW01Z4.h (for MKW01Z128), there is a section "Backward Compatibility",
one item of it is:
#define LPTimer_IRQn                             LPTMR0_IRQn

That's why i think LPTMR0_IRQn is the proper identifier.

**Comment by gebart** [comment]
Okay, let's all use LPTMR0 then. I'll add a forward compatibility define in
my k60 port. (all k60 headers seem really old and it doesn't seem like they
are updating them any more)

**Comment by jfischer-phytec-iot** [comment]
@gebart Can be closed?

**Comment by gebart** [comment]
Yeah

**Pull request closed without merging**
