### PR TITLE
kinetis_common: SPI refactor

### PR DESCRIPTION
**Pull request by gebart**
I have refactored the SPI driver to work better with my platform. 

 - Added support for up to SPI_7 in master mode. I did not do any improvements to slave mode, I have not bothered to set up a test bed for slave mode.
 - It is possible to configure two (RIOT) SPI devices to point at the same hardware module and only diff in the CTAS value, this lets us switch between two timing configurations on the fly.
 - Added support to spi_transfer_x to allow NULL pointers in one or the other direction, if we are only interested in writing/reading.
 - Locking is handled per hardware device, if two RIOT SPI devices use the same hardware bus the lock is shared between the two virtual devices to allow thread safety.

Necessary changes to periph-conf.h:

 - Add SPI_x_INDEX which evaluates to the number of the hardware module. This is necessary in order to index the hardware locks array.

Known problems:

 - IRQ handlers are a bit of a mess. Only define the IRQ handler for one of the virtual devices of the same hardware device.

Future improvements:

 - Modify `spi_transfer_bytes` and `spi_transfer_regs` to use DMA.

### CODE REVIEW

**Comment by jfischer-phytec-iot** [comment]
@gebart I want to test it on kw2x tomorrow.

**Comment by jfischer-phytec-iot** [comment]
I have had the time to test it. I have enabled hardware CS and measured the signals. I would be glad if we install a hardware option to activate CS. Something like:
#define KINETIS_SPI_HWCS    1
in periph_conf.h and a macro in spi.c to enable hardware CS.


SPI0, 10MHz, hardware CS - green, gpio CS - blue

**Comment by gebart** [comment]
Can we save the hardware CS modifications until after we have merged the
initial kinetis common PR?
I think #2265 is already a bit on the large side for reviewing the code
before merging. Then we can have the discussion about hardware CS focused
in one thread.

**Comment by jfischer-phytec-iot** [comment]
Ok.
Can you please expand the configuration example in dox.txt, with the example of two virtual SPI.

**Comment by gebart** [comment]
I will change the spi_transfer_reg function and add an example to doc.txt tomorrow.

**Comment by gebart** [comment]
Addressed comments.

**Pull request merged**
